= File Allocation Table (FAT) file system format
Analysis of the FAT file system

:toc:
:toclevels: 4

:numbered!:
[abstract]
== Summary

The File Allocation Table (FAT) is widely used a file sytem. This
specification is based on publicly available work on the format and was
enhanced by analyzing test data.

This document is intended as a working document of the data format specification
for the libfsfat project.

[preface]
== Document information

[cols="1,5"]
|===
| Author(s): | Joachim Metz <joachim.metz@gmail.com>
| Abstract: | This document contains information about the File Allocation Table (FAT) format.
| Classification: | Public
| Keywords: | File Allocation Table (FAT)
|===

[preface]
== License

....
Copyright (C) 2021-2022, Joachim Metz <joachim.metz@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under the
terms of the GNU Free Documentation License, Version 1.3 or any later version
published by the Free Software Foundation; with no Invariant Sections, no
Front-Cover Texts, and no Back-Cover Texts. A copy of the license is included
in the section entitled "GNU Free Documentation License".
....

[preface]
== Revision history

[cols="1,1,1,5",options="header"]
|===
| Version | Author | Date | Comments
| 0.0.1 | J.B. Metz | August 2021 | Initial version based on older notes about the format.
| 0.0.2 | J.B. Metz | May 2022 | Additional information.
| 0.0.3 | J.B. Metz | June 2022 | Additional information.
| 0.0.4 | J.B. Metz | July 2022 | Additional information.
|===

:numbered:
== Overview

The File Allocation Table (FAT) is widely used a file sytem. There are multiple
known variants or derivatives of FAT, such as:

* (original) 8-bit FAT
* FAT-12
* FAT-16
* FAT-32
* exFAT

A FAT file system consists of:

* One or more reserved sectors
  * a boot sector
  * file system informartion for FAT-32
* One or more file allocation tables
* Root directory data for FAT-12 and FAT-16
* File and directory data

[NOTE]
FAT-32 stores the root directory as part of the file and directory data.

[cols="1,5",options="header"]
|===
| Characteristics | Description
| Byte order | little-endian
| Date and time values | FAT date and time
| Character strings | ASCII strings are Single Byte Character (SBC) or Multi Byte Character (MBC) string stored with a OEM codepage. Sometimes referred to as ANSI string representation. +
Though technically maybe incorrect, this document will use term (extended) ASCII string. +
Unicode strings are stored in UCS-2.
|===

=== Determing FAT version

To distinguish between FAT-12, FAT-16 and FAT-32, compute the number of clusters
in the data area:

....
data area size = total number of sectors - ( number of reserved sectors + size of allocations tables + size of root directory )
....

....
number of clusters = round down ( data area size / sectors per cluster )
....

* FAT-12 is used if the number of clusters is less than 4085
* FAT-16 is used if the number of clusters is less than 65525
* FAT-32 is used otherwise

=== Determining the root directory location

==== FAT-12 and FAT-16 root directory

....
start sector = number of reserved sectors + ( number allocation tables x allocation table size )
....

==== FAT-32 root directory

....
start sector = root directory cluster x number of sectors per cluster
....

== Boot sector

=== FAT-12 and FAT-16 boot sector

The boot sector is stored in the first sector of the volume.

The boot sector is at least 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 3 | "\xeb\x3c\x90" | Boot entry point (JMP +62, NOP)
| 3 | 8 | | File system signature (or OEM name)
| 11 | 2 | | Bytes per sector +
Must be 512, 1024, 2048 or 4096 according to `[MICROSOFT00]`.
| 13 | 1 | | Sectors per cluster block +
Must be 1, 2, 4, 8, 16, 32, 64 or 128 according to `[MICROSOFT00]`.
| 14 | 2 | | Number of reserved sectors +
The reserved region starts at the first sector of the volume (sector 0) +
Must be 1 or more according to `[MICROSOFT00]`, typically 1 or 32.
| 16 | 1 | | Number of file allocation tables +
Must be 1 or more according to `[MICROSOFT00]`, typically 2.
| 17 | 2 | | Number of root directory entries
| 19 | 2 | | Total number of sectors (16-bit)
| 21 | 1 | | Media descriptor
| 22 | 2 | | File allocation table size (16-bit) +
Contains the number of sectors of a File Allocation Table
| 24 | 2 | | Number of sectors per track
| 26 | 2 | | Number of heads
| 28 | 4 | | Number of hidden sectors
| 32 | 4 | | Total number of sectors (32-bit)
4+| _FAT-12 and FAT-16_
| 36 | 1 | | Drive number
| 37 | 1 | 0 | [yellow-background]*Unknown (reserved for Windows NT)*
| 38 | 1 | | Extended boot signature +
If set to 0x29 the following 3 values are considered to be set
4+| _If extended boot signature == 0x29_
| 39 | 4 | | Volume serial number
| 43 | 11 | | Volume label +
Contains an ASCII string or "NO\x20NAME\x20\x20\x20\x20" if not set
| 54 | 8 | | File system hint +
Contains an ASCII string with a hint about the file system +
Note that this value is purely informational and not enforced by the format
4+| _If extended boot signature != 0x29_
| 39 | 23 | | [yellow-background]*Unknown*
4+| _Common_
| 62 | 448 | | Used for boot code
| 510 | 2 | 0x55 0xaa | Sector signature
|===

[NOTE]
The sector signature must be set at offset 512 but can, in addition, it can
be set in the last 2 bytes of the sector.

[NOTE]
The term hidden sectors refers to the sectors stored before the FAT volume,
such as those used to store a parition table.

[NOTE]
The volume serial number can be derived from the system current date and time.

=== FAT-32 boot sector

The boot sector is stored in the first sector of the volume.

The boot sector is at least 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 3 | "\xeb\x58\x90" | Boot entry point (JMP +90, NOP)
| 3 | 8 | | File system signature (or OEM name)
| 11 | 2 | | Bytes per sector +
Must be 512, 1024, 2048 or 4096 according to `[MICROSOFT00]`.
| 13 | 1 | | Sectors per cluster block +
Must be 1, 2, 4, 8, 16, 32, 64 or 128 according to `[MICROSOFT00]`.
| 14 | 2 | | Number of reserved sectors +
The reserved region starts at the first sector of the volume (sector 0) +
Must be 1 or more according to `[MICROSOFT00]`, typically 1 or 32.
| 16 | 1 | | Number of file allocation tables +
Must be 1 or more according to `[MICROSOFT00]`, typically 2.
| 17 | 2 | 0 | Number of root directory entries +
Must be 0 for FAT-32
| 19 | 2 | 0 | Total number of sectors (16-bit) +
Must be 0 for FAT-32
| 21 | 1 | | Media descriptor
| 22 | 2 | 0 | File allocation table size (16-bit) +
Contains the number of sectors of a File Allocation Table +
Must be 0 for FAT-32
| 24 | 2 | | Number of sectors per track
| 26 | 2 | | Number of heads
| 28 | 4 | | Number of hidden sectors
| 32 | 4 | | Total number of sectors (32-bit)
| 36 | 4 | | File allocation table size (32-bit) +
Contains the number of sectors of a File Allocation Table, must be non 0
| 40 | 2 | | Extended flags
| 42 | 1 | 0 | Format revision minor number
| 43 | 1 | 0 | Format revision major number
| 44 | 4 | | Root directory start cluster
| 48 | 2 | | File system information (FSINFO) sector number
| 50 | 2 | | Boot record sector number
| 52 | 12 | 0 | [yellow-background]*Unknown (reserved)*
| 64 | 1 | | Drive number
| 65 | 1 | 0 | [yellow-background]*Unknown (reserved for Windows NT)*
| 66 | 1 | | Extended boot signature +
If set to 0x29 the following 3 values are considered to be set
4+| _If extended boot signature == 0x29_
| 67 | 4 | | Volume serial number
| 71 | 11 | | Volume label +
Contains an ASCII string or "NO\x20NAME\x20\x20\x20\x20" if not set
| 82 | 8 | "FAT32\x20\x20\x20" | File system hint +
Contains an ASCII string with a hint about the file system +
Note that this value is purely informational and not enforced by the format
4+| _If extended boot signature != 0x29_
| 67 | 23 | | [yellow-background]*Unknown*
4+| _Common_
| 90 | 420 | | Used for boot code
| 510 | 2 | 0x55 0xaa | Sector signature
|===

[NOTE]
The sector signature must be set at offset 512 but can, in addition, it can
be set in the last 2 bytes of the sector.

[NOTE]
The term hidden sectors refers to the sectors stored before the FAT volume,
such as those used to store a parition table.

[NOTE]
The volume serial number can be derived from the system current date and time.

=== exFAT boot sector

The boot sector is stored in the first sector of the volume.

The boot sector is at least 512 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 3 | "\xeb\x76\x90" | Boot entry point (JMP +120, NOP)
| 3 | 8 | "EXFAT\x20\x20\x20" | File system signature (or OEM name)
| 11 | 53 | 0 | [yellow-background]*Unknown (reserved)*
Must be 0 according to `[MICROSOFT22]`.
| 64 | 8 | | Partition offset
| 72 | 8 | | Total number of sectors
| 80 | 4 | | File allocation table size start sector
| 84 | 4 | | File allocation table size +
Contains the number of sectors of a File Allocation Table, must be non 0
| 88 | 4 | | [yellow-background]*Unknown (cluster heap start sector)*
| 92 | 4 | | [yellow-background]*Unknown (cluster heap number of sectors)*
| 96 | 4 | | Root directory start cluster
| 100 | 4 | | Volume serial number
| 104 | 1 | | Format revision minor number
| 105 | 1 | 1 | Format revision major number
| 106 | 2 | | Volume flags
| 108 | 1 | | Bytes per sector +
Value is stored as `2^n`, for example 9 is `2^9 = 512` +
The bytes per sector value must be 512, 1024, 2048 or 4096 according to `[MICROSOFT22]`.
| 109 | 1 | | Sectors per cluster block +
Value is stored as `2^n`, for example 3 is `2^3 = 8` +
The sectors per cluster block must be 1 upto 32M (`2^25`) according to `[MICROSOFT22]`.
| 110 | 1 | | Number of file allocation tables
| 111 | 1 | | Drive number
| 112 | 1 | | [yellow-background]*Unknown (percent in use)* +
Contains the percentage of allocated cluster blocks in the cluster heap of 0xff if not available
| 113 | 7 | | [yellow-background]*Unknown (reserved)*
| 120 | 390 | | Used for boot code
| 510 | 2 | 0x55 0xaa | Sector signature
|===

=== OEM names

[cols="1,5",options="header"]
|===
| Value | Description
| "MSWIN4.1" |
| "MSDOS 5.0" |
| "EXFAT   " |
|===

=== Media descriptors

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0xf0 | | removable media
| 0xf8 | | fixed (non-removable) media
| 0xf9 | |
| 0xfa | |
| 0xfb | |
| 0xfc | |
| 0xfd | |
| 0xfe | |
| 0xff | |
|===

=== exFAT Volume flags

[cols="1,1,5",options="header"]
|===
| Value | Identifier | Description
| 0x0001 | ActiveFat | Active FAT, 0 for the first FAT, 1 for the second FAT
| 0x0002 | VolumeDirty | Is dirty
| 0x0004 | MediaFailure | Has media failures
| 0x0008 | ClearToZero | Must be cleared
| 0xfff0 | | [yellow-background]*Unknown (reserved)*
|===

== File allocation table

A file allocation table consists of:

* One ore more file allocation table entries

=== FAT 12 file allocation table entry

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 12 bits | | Data cluster number
|===

[cols="1,5",options="header"]
|===
| Value(s) | Description
| 0x000 | Unused (free) cluster
| 0x001 | [yellow-background]*Unknown (invalid)*
| 0x002 - 0xfef | Used cluster
| 0xff0 - 0xff6 | Reserved
| 0xff7 | Bad cluster
| 0xff8 - 0xfff | End of cluster chain
|===

=== FAT 16 file allocation table entry

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 2 | | Data cluster number
|===

[cols="1,5",options="header"]
|===
| Value(s) | Description
| 0x0000 | Unused (free) cluster
| 0x0001 | [yellow-background]*Unknown (invalid)*
| 0x0002 - 0xffef | Used cluster
| 0xfff0 - 0xfff6 | Reserved
| 0xfff7 | Bad cluster
| 0xfff8 - 0xffff | End of cluster chain
|===

=== FAT 32 file allocation table entry

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 4 | | Data cluster number
|===

[NOTE]
Only the lower 28-bits are used

[cols="1,5",options="header"]
|===
| Value(s) | Description
| 0x00000000 | Unused (free) cluster
| 0x00000001 | [yellow-background]*Unknown (invalid)*
| 0x00000002 - 0x0fffffef | Used cluster
| 0x0ffffff0 - 0x0ffffff6 | Reserved
| 0x0ffffff7 | Bad cluster
| 0x0ffffff8 - 0x0fffffff | End of cluster chain
| 0x10000000 - 0xffffffff | [yellow-background]*Unknown*
|===

== Directory

A directory consists of:

* self (".") directory entry (not used in root directory)
* parent ("..") directory entry (not used in root directory)
* Zero or more directory entries
* Terminator directory entry

=== Directory entry

A directory entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 8 | | Short file name (padded with spaces)
Contains an ASCII string where the first character can have a special meaning
| 8 | 3 | | Short file extension (padded with spaces)
| 11 | 1 | | File attributes +
See section: <<file_attributes,File attributes>>
| 12 | 1 | | [yellow-background]*Unknown (Case for short file name and extension)*
| 13 | 1 | | Creation time fraction of seconds +
Contains fraction of 2-seconds in 10 ms intervals
| 14 | 2 | | Creation time
| 16 | 2 | | Creation date
| 18 | 2 | | Last access date
| 20 | 2 | | [yellow-background]*Unknown (OS/2 extended attribute)* +
Not used by FAT-12
| 22 | 2 | | Last written time
| 24 | 2 | | Last written date
| 26 | 2 | | File content data start cluster
| 28 | 4 | | File content data size
|===

=== Short (8.3) file name

A FAT short (8.3) file name is stored in an OEM character set (codepage). The
<<short_name_first_character,first character>> can have a special meaning.

Valid FAT short file name characters are:

[cols="1,5",options="header"]
|===
| Value | Description
| 'A-Z' | Upper case character
| '0-9' | Numeric character
| ' ' | Space, where trailing spaces are considered padding and therefore ignored.
| '.' | Dot, with the exception of "." and  "..". Trailing dot characters are ignored.
| '!' |
| '#' |
| '$' |
| '%' |
| '&' |
| '\'' | 
| '(' |
| ')' |
| '-' |
| '@' |
| '^' |
| '_' |
| '`' | 
| '{' |
| '}' |
| '~' |
| 0x80 - 0xff | Extended ASCII character, which are codepage dependent.
|===

==== [[short_name_first_character]]First character

[cols="1,5",options="header"]
|===
| Value | Description
| 0x00 | Last (or terminator) directory entry
| 0x01 - 0x13 | VFAT long file name directory entry
| 0x05 | Directory entry pending deallocation (deprecated since DOS 3.0) or substitution of a 0xe5 extended ASCII character value
| 0x41 - 0x54 | Last VFAT long file name directory entry
| 0xe5 | Unallocated directory entry
|===

=== [[file_attributes]]File attributes

[cols="1,5",options="header"]
|===
| Value | Description
| 0x01 | Read-only
| 0x02 | Hidden
| 0x04 | System
| 0x08 | Is volume label
| 0x10 | Is directory
| 0x20 | Archive
| 0x40 | Is device
| 0x80 | [yellow-background]*Unused (reserved)*
|===

=== VFAT long file name entry

VFAT long file names entries are stored in directory entries. Multiple VFAT
long file name entries can be used to store a single long file name, where
the highest (last) sequence number is stored first. A maximum of 20 VFAT long
file name entries can be used to store a long file name of 255 UCS-2 characters.

VFAT long file name entries are stored before the directory entry containing
the short file name and additional file entry information.

A VFAT long file name entry is 32 bytes of size and consists of:

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 1 | | Sequence number
| 1 | 10 | | First name segment string +
Either 10 narrow string or 5 UCS-2 characters
| 11 | 1 | 0x0f | [yellow-background]*Unknown (attributes)*
| 12 | 1 | 0x00 | [yellow-background]*Unknown (type)*
| 13 | 1 | | Checksum of the short (8.3) file name
| 14 | 12 | | Second name segment string +
Either 12 narrow string or 6 UCS-2 characters
| 26 | 2 | 0 | [yellow-background]*Unknown (first cluster)*
| 28 | 4 | | Third name segment string +
Either 4 narrow string or 2 UCS-2 characters
|===

==== VFAT long file name sequence number

[cols="1,1,1,5",options="header"]
|===
| Offset | Size | Value | Description
| 0 | 5 bits | | Number
| 0.5 | 1 bit | 0 | [yellow-background]*Unknown (reserved)*
| 0.6 | 1 bit | 0 | [yellow-background]*Unknown (last logical, first physical LFN entry)*
| 0.7 | 1 bit | 0 | [yellow-background]*Unknown*
|===

:numbered!:
[appendix]
== References

`[MICROSOFT00]`

[cols="1,5",options="header"]
|===
| Title: | Microsoft Extensible Firmware Initiative FAT32 File System Specification
| URL: | http://download.microsoft.com/download/1/6/1/161ba512-40e2-4cc9-843a-923143f3456c/fatgen103.doc
|===

`[MICROSOFT22]`

[cols="1,5",options="header"]
|===
| Title: | exFAT file system specification
| URL: | https://docs.microsoft.com/en-gb/windows/win32/fileio/exfat-specification#31-main-and-backup-boot-sector-sub-regions
|===

`[WIKIPEDIA]`

[cols="1,5",options="header"]
|===
| Title: | Design of the FAT file system
| URL: | https://en.wikipedia.org/wiki/Design_of_the_FAT_file_system
|===

[cols="1,5",options="header"]
|===
| Title: | exFAT
| URL: | https://en.wikipedia.org/wiki/ExFAT
|===

[cols="1,5",options="header"]
|===
| Title: | File Allocation Table
| URL: | https://en.wikipedia.org/wiki/File_Allocation_Table
|===

[appendix]
== GNU Free Documentation License

Version 1.3, 3 November 2008
Copyright © 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
<http://fsf.org/>

Everyone is permitted to copy and distribute verbatim copies of this license
document, but changing it is not allowed.

=== 0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other functional
and useful document "free" in the sense of freedom: to assure everyone the
effective freedom to copy and redistribute it, with or without modifying it,
either commercially or noncommercially. Secondarily, this License preserves for
the author and publisher a way to get credit for their work, while not being
considered responsible for modifications made by others.

This License is a kind of "copyleft", which means that derivative works of the
document must themselves be free in the same sense. It complements the GNU
General Public License, which is a copyleft license designed for free software.

We have designed this License in order to use it for manuals for free software,
because free software needs free documentation: a free program should come with
manuals providing the same freedoms that the software does. But this License is
not limited to software manuals; it can be used for any textual work,
regardless of subject matter or whether it is published as a printed book. We
recommend this License principally for works whose purpose is instruction or
reference.

=== 1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that contains
a notice placed by the copyright holder saying it can be distributed under the
terms of this License. Such a notice grants a world-wide, royalty-free license,
unlimited in duration, to use that work under the conditions stated herein. The
"Document", below, refers to any such manual or work. Any member of the public
is a licensee, and is addressed as "you". You accept the license if you copy,
modify or distribute the work in a way requiring permission under copyright law.

A "Modified Version" of the Document means any work containing the Document or
a portion of it, either copied verbatim, or with modifications and/or
translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of the
Document that deals exclusively with the relationship of the publishers or
authors of the Document to the Document's overall subject (or to related
matters) and contains nothing that could fall directly within that overall
subject. (Thus, if the Document is in part a textbook of mathematics, a
Secondary Section may not explain any mathematics.) The relationship could be a
matter of historical connection with the subject or with related matters, or of
legal, commercial, philosophical, ethical or political position regarding them.

The "Invariant Sections" are certain Secondary Sections whose titles are
designated, as being those of Invariant Sections, in the notice that says that
the Document is released under this License. If a section does not fit the
above definition of Secondary then it is not allowed to be designated as
Invariant. The Document may contain zero Invariant Sections. If the Document
does not identify any Invariant Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed, as
Front-Cover Texts or Back-Cover Texts, in the notice that says that the
Document is released under this License. A Front-Cover Text may be at most 5
words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy, represented
in a format whose specification is available to the general public, that is
suitable for revising the document straightforwardly with generic text editors
or (for images composed of pixels) generic paint programs or (for drawings)
some widely available drawing editor, and that is suitable for input to text
formatters or for automatic translation to a variety of formats suitable for
input to text formatters. A copy made in an otherwise Transparent file format
whose markup, or absence of markup, has been arranged to thwart or discourage
subsequent modification by readers is not Transparent. An image format is not
Transparent if used for any substantial amount of text. A copy that is not
"Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain ASCII without
markup, Texinfo input format, LaTeX input format, SGML or XML using a publicly
available DTD, and standard-conforming simple HTML, PostScript or PDF designed
for human modification. Examples of transparent image formats include PNG, XCF
and JPG. Opaque formats include proprietary formats that can be read and edited
only by proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the machine-generated HTML,
PostScript or PDF produced by some word processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself, plus such
following pages as are needed to hold, legibly, the material this License
requires to appear in the title page. For works in formats which do not have
any title page as such, "Title Page" means the text near the most prominent
appearance of the work's title, preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of the
Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose title
either is precisely XYZ or contains XYZ in parentheses following text that
translates XYZ in another language. (Here XYZ stands for a specific section
name mentioned below, such as "Acknowledgements", "Dedications",
"Endorsements", or "History".) To "Preserve the Title" of such a section when
you modify the Document means that it remains a section "Entitled XYZ"
according to this definition.

The Document may include Warranty Disclaimers next to the notice which states
that this License applies to the Document. These Warranty Disclaimers are
considered to be included by reference in this License, but only as regards
disclaiming warranties: any other implication that these Warranty Disclaimers
may have is void and has no effect on the meaning of this License.

=== 2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either commercially or
noncommercially, provided that this License, the copyright notices, and the
license notice saying this License applies to the Document are reproduced in
all copies, and that you add no other conditions whatsoever to those of this
License. You may not use technical measures to obstruct or control the reading
or further copying of the copies you make or distribute. However, you may
accept compensation in exchange for copies. If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and you may
publicly display copies.

=== 3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have printed
covers) of the Document, numbering more than 100, and the Document's license
notice requires Cover Texts, you must enclose the copies in covers that carry,
clearly and legibly, all these Cover Texts: Front-Cover Texts on the front
cover, and Back-Cover Texts on the back cover. Both covers must also clearly
and legibly identify you as the publisher of these copies. The front cover must
present the full title with all words of the title equally prominent and
visible. You may add other material on the covers in addition. Copying with
changes limited to the covers, as long as they preserve the title of the
Document and satisfy these conditions, can be treated as verbatim copying in
other respects.

If the required texts for either cover are too voluminous to fit legibly, you
should put the first ones listed (as many as fit reasonably) on the actual
cover, and continue the rest onto adjacent pages.

If you publish or distribute Opaque copies of the Document numbering more than
100, you must either include a machine-readable Transparent copy along with
each Opaque copy, or state in or with each Opaque copy a computer-network
location from which the general network-using public has access to download
using public-standard network protocols a complete Transparent copy of the
Document, free of added material. If you use the latter option, you must take
reasonably prudent steps, when you begin distribution of Opaque copies in
quantity, to ensure that this Transparent copy will remain thus accessible at
the stated location until at least one year after the last time you distribute
an Opaque copy (directly or through your agents or retailers) of that edition
to the public.

It is requested, but not required, that you contact the authors of the Document
well before redistributing any large number of copies, to give them a chance to
provide you with an updated version of the Document.

=== 4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under the
conditions of sections 2 and 3 above, provided that you release the Modified
Version under precisely this License, with the Modified Version filling the
role of the Document, thus licensing distribution and modification of the
Modified Version to whoever possesses a copy of it. In addition, you must do
these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct from that
of the Document, and from those of previous versions (which should, if there
were any, be listed in the History section of the Document). You may use the
same title as a previous version if the original publisher of that version
gives permission.

B. List on the Title Page, as authors, one or more persons or entities
responsible for authorship of the modifications in the Modified Version,
together with at least five of the principal authors of the Document (all of
its principal authors, if it has fewer than five), unless they release you from
this requirement.

C. State on the Title page the name of the publisher of the Modified Version,
as the publisher.

D. Preserve all the copyright notices of the Document.

E. Add an appropriate copyright notice for your modifications adjacent to the
other copyright notices.

F. Include, immediately after the copyright notices, a license notice giving
the public permission to use the Modified Version under the terms of this
License, in the form shown in the Addendum below.

G. Preserve in that license notice the full lists of Invariant Sections and
required Cover Texts given in the Document's license notice.

H. Include an unaltered copy of this License.

I. Preserve the section Entitled "History", Preserve its Title, and add to it
an item stating at least the title, year, new authors, and publisher of the
Modified Version as given on the Title Page. If there is no section Entitled
"History" in the Document, create one stating the title, year, authors, and
publisher of the Document as given on its Title Page, then add an item
describing the Modified Version as stated in the previous sentence.

J. Preserve the network location, if any, given in the Document for public
access to a Transparent copy of the Document, and likewise the network
locations given in the Document for previous versions it was based on. These
may be placed in the "History" section. You may omit a network location for a
work that was published at least four years before the Document itself, or if
the original publisher of the version it refers to gives permission.

K. For any section Entitled "Acknowledgements" or "Dedications", Preserve the
Title of the section, and preserve in the section all the substance and tone of
each of the contributor acknowledgements and/or dedications given therein.

L. Preserve all the Invariant Sections of the Document, unaltered in their text
and in their titles. Section numbers or the equivalent are not considered part
of the section titles.

M. Delete any section Entitled "Endorsements". Such a section may not be
included in the Modified Version.

N. Do not retitle any existing section to be Entitled "Endorsements" or to
conflict in title with any Invariant Section.

O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or appendices that
qualify as Secondary Sections and contain no material copied from the Document,
you may at your option designate some or all of these sections as invariant. To
do this, add their titles to the list of Invariant Sections in the Modified
Version's license notice. These titles must be distinct from any other section
titles.

You may add a section Entitled "Endorsements", provided it contains nothing but
endorsements of your Modified Version by various parties—for example,
statements of peer review or that the text has been approved by an organization
as the authoritative definition of a standard.

You may add a passage of up to five words as a Front-Cover Text, and a passage
of up to 25 words as a Back-Cover Text, to the end of the list of Cover Texts
in the Modified Version. Only one passage of Front-Cover Text and one of
Back-Cover Text may be added by (or through arrangements made by) any one
entity. If the Document already includes a cover text for the same cover,
previously added by you or by arrangement made by the same entity you are
acting on behalf of, you may not add another; but you may replace the old one,
on explicit permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License give
permission to use their names for publicity for or to assert or imply
endorsement of any Modified Version.

=== 5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this License,
under the terms defined in section 4 above for modified versions, provided that
you include in the combination all of the Invariant Sections of all of the
original documents, unmodified, and list them all as Invariant Sections of your
combined work in its license notice, and that you preserve all their Warranty
Disclaimers.

The combined work need only contain one copy of this License, and multiple
identical Invariant Sections may be replaced with a single copy. If there are
multiple Invariant Sections with the same name but different contents, make the
title of each such section unique by adding at the end of it, in parentheses,
the name of the original author or publisher of that section if known, or else
a unique number. Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History" in the
various original documents, forming one section Entitled "History"; likewise
combine any sections Entitled "Acknowledgements", and any sections Entitled
"Dedications". You must delete all sections Entitled "Endorsements".

=== 6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other documents
released under this License, and replace the individual copies of this License
in the various documents with a single copy that is included in the collection,
provided that you follow the rules of this License for verbatim copying of each
of the documents in all other respects.

You may extract a single document from such a collection, and distribute it
individually under this License, provided you insert a copy of this License
into the extracted document, and follow this License in all other respects
regarding verbatim copying of that document.

=== 7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate and
independent documents or works, in or on a volume of a storage or distribution
medium, is called an "aggregate" if the copyright resulting from the
compilation is not used to limit the legal rights of the compilation's users
beyond what the individual works permit. When the Document is included in an
aggregate, this License does not apply to the other works in the aggregate
which are not themselves derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these copies of the
Document, then if the Document is less than one half of the entire aggregate,
the Document's Cover Texts may be placed on covers that bracket the Document
within the aggregate, or the electronic equivalent of covers if the Document is
in electronic form. Otherwise they must appear on printed covers that bracket
the whole aggregate.

=== 8. TRANSLATION

Translation is considered a kind of modification, so you may distribute
translations of the Document under the terms of section 4. Replacing Invariant
Sections with translations requires special permission from their copyright
holders, but you may include translations of some or all Invariant Sections in
addition to the original versions of these Invariant Sections. You may include
a translation of this License, and all the license notices in the Document, and
any Warranty Disclaimers, provided that you also include the original English
version of this License and the original versions of those notices and
disclaimers. In case of a disagreement between the translation and the original
version of this License or a notice or disclaimer, the original version will
prevail.

If a section in the Document is Entitled "Acknowledgements", "Dedications", or
"History", the requirement (section 4) to Preserve its Title (section 1) will
typically require changing the actual title.

=== 9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document except as
expressly provided under this License. Any attempt otherwise to copy, modify,
sublicense, or distribute it is void, and will automatically terminate your
rights under this License.

However, if you cease all violation of this License, then your license from a
particular copyright holder is reinstated (a) provisionally, unless and until
the copyright holder explicitly and finally terminates your license, and (b)
permanently, if the copyright holder fails to notify you of the violation by
some reasonable means prior to 60 days after the cessation.

Moreover, your license from a particular copyright holder is reinstated
permanently if the copyright holder notifies you of the violation by some
reasonable means, this is the first time you have received notice of violation
of this License (for any work) from that copyright holder, and you cure the
violation prior to 30 days after your receipt of the notice.

Termination of your rights under this section does not terminate the licenses
of parties who have received copies or rights from you under this License. If
your rights have been terminated and not permanently reinstated, receipt of a
copy of some or all of the same material does not give you any rights to use it.

=== 10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the GNU Free
Documentation License from time to time. Such new versions will be similar in
spirit to the present version, but may differ in detail to address new problems
or concerns. See http://www.gnu.org/copyleft/.

Each version of the License is given a distinguishing version number. If the
Document specifies that a particular numbered version of this License "or any
later version" applies to it, you have the option of following the terms and
conditions either of that specified version or of any later version that has
been published (not as a draft) by the Free Software Foundation. If the
Document does not specify a version number of this License, you may choose any
version ever published (not as a draft) by the Free Software Foundation. If the
Document specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a version
permanently authorizes you to choose that version for the Document.

=== 11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any World Wide
Web server that publishes copyrightable works and also provides prominent
facilities for anybody to edit those works. A public wiki that anybody can edit
is an example of such a server. A "Massive Multiauthor Collaboration" (or
"MMC") contained in the site means any set of copyrightable works thus
published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0 license
published by Creative Commons Corporation, a not-for-profit corporation with a
principal place of business in San Francisco, California, as well as future
copyleft versions of that license published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in part, as
part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this License, and
if all works that were first published under this License somewhere other than
this MMC, and subsequently incorporated in whole or in part into the MMC, (1)
had no cover texts or invariant sections, and (2) were thus incorporated prior
to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site under
CC-BY-SA on the same site at any time before August 1, 2009, provided the MMC
is eligible for relicensing.

